### ISSUE TITLE
Consulta subida de imagenes

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2513-1/Syllabus#2]
Hola buenas tardes!,
Quería consultar sobre si me podrían ayudar con un problema que he tenido con la subida de imagenes. Cuando subo una imagen por axios y recibo la información guardada me retorna que la imagen se guardó de la siguiente manera:
![image](https://user-images.githubusercontent.com/69593192/172486269-2251fed4-1756-4eed-8186-546975f2cfb1.png)
Y me sucede incluso subiendo el archivo de diferentes maneras (en forma de archivo File o en arrayBuffer).
Si alguien me puede ayudar con eso lo agradeceria :c.

**Comment by hanavarrete** [comment]
Hola! No entiendo cual es tu problema. Podrías especificar más?  Es normal encontrarse con buffers cuando haces subida de archivos. Creo que en ese caso, internet te sirve más jajaj. Te dejo este link  https://stackoverflow.com/questions/65392241/how-convert-type-data-buffer-to-image-in-react-js

Espero te sirva

**Comment by AlonsoZamorano** [comment]
Holaaaa, al final re haciendo mi código completo me funcionó todo correctamente! Muchas gracias!
